using MauiApp_test.Abstractions;
using SQLite;
using SQLiteNetExtensions.Attributes;

namespace MauiApp_test.MVVM.Models
{
    [Table("Courses")]
    public class Courses : TableData
    {
        public string Name { get; set; }
        public string CourseCode { get; set; }
        public string Instructor { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime DueDate { get { return EndDate.AddDays(-1); } } 
        // Autogenerated due date is one day before the end date

        public string Status { get; set; }
        public string Notes { get; set; }
        public int Term { get; set; }
        public bool Notifications { get; set; }

        // Foreign key and relationship to the Instructor table
        [ForeignKey(typeof(Instructor))]
        public string InstructorName { get; set; }

        public bool HasCourse { get; set; } = true;


        public bool IsButtonVisible { get; set; }
    }


}
